---
apiVersion: v1
kind: Service
metadata:
  name: hpa-deployment-svc
spec:
  type: NodePort
  selector:
    app: hpa-deployment
  ports:
  - port: 3000 # Expose port 3000
    targetPort: 3000 # Target port 3000 on pods
...
